### ISSUE TITLE
Change RethinkDB driver to rethinkdbdash

### ISSUE THREAD

**Issue by grantcarthew** [yamalight/rethinkdb-pubsub#2]
For reference: https://github.com/neumino/rethinkdbdash
FAQ: https://github.com/neumino/rethinkdbdash#faq

It supports connection pooling.

Again, I could look at adding this once I get some experience with pubsub.

**Comment by yamalight** [comment]
Why would connection pooling be needed in case of pubsub? And what are other benefits from switching here?

If the API are exactly same as from official, it might be possible to tweak the code to allow replacement of the driver when required.

**Comment by paramaggarwal** [comment]
I was already using `rethinkdbdash` in my project and wanted simple event persistence and passing between servers so I made https://github.com/paramaggarwal/emitter-rethinkdb for it.

While it does not have the sophisticated exchange/topic nomenclature, it is more like a global event emitter between your servers with automatic reconnection and connection pooling thanks to `rethinkdbdash`.

**Comment by grantcarthew** [comment]
Nice one @paramaggarwal
